services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=parking_db
      - DATABASE_URL=postgresql://user:password@db:5432/parking_db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: parking_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: